# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
oplus_bsp_dfr_dump_reason-y := dump_reason.o
obj-$(CONFIG_OPLUS_FEATURE_DUMP_REASON) += oplus_bsp_dfr_dump_reason.o
